In [1]:
import numpy

In [3]:
import numpy 
arr = numpy.array([1,2,3,4,5])

print(arr)


[1 2 3 4 5]


In [4]:
import numpy as np 
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [5]:
print(np.__version__)

1.20.1


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
tmp = np.ndarray([1,2,3,4,5])
print(tmp)

[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]]]


In [8]:
# dimensions in Arrays.
# 0-D array (Scalar).
import numpy as np
arr = np.array(36)

print(arr)

36


In [9]:
# 1-D array.
import numpy as np
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [10]:
# 2-D array.
import numpy as np
arr = np.array([ [1,2,3], [4,5,6] ] )

print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
# 3-D array.
import numpy as np
arr = np.array([ [ [1,2,3], [4,5,6], [7,8,9], [10,11,12] ] ])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [12]:
print(arr[0])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
print(arr[0][0])

[1 2 3]


In [15]:
print(arr[0][0][0])

1


In [17]:
print(arr[0][1])

[4 5 6]


In [18]:
print(arr[0][2])

[7 8 9]


In [19]:
print(arr[0][3])

[10 11 12]


In [20]:
print(arr[0][3][2])

12


In [21]:
tmp = np.array([1,2, "abc", "def"])

In [22]:
print(tmp)

['1' '2' 'abc' 'def']


In [23]:
print(arr.ndim)

3


In [27]:
a = np.array(57)
b = np.array([1,2,3,4,5])
c = np.array([ [1,2,3], [4,5,6]])
d = np.array([[ [1,2,3], [4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [30]:
import numpy as np
arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [32]:
arr = np.array([1,2,3,4])

print(arr[2] + arr[3])

7


In [41]:
arr = np.array([[ [1,2,3], [4,5,6], [7,8,9]]])
print(arr[0])
print(arr[0][1])
print(arr[0][1][2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
6


In [44]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10] ])
print(arr[1,-1])
print(arr[1,-3])
print(arr[0,-3])


10
8
3


In [45]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:5])

[2 3 4 5]


In [48]:
print(arr[1:8])
print(arr[1:8:2])
print(arr[0:8:2])

[2 3 4 5 6 7 8]
[2 4 6 8]
[1 3 5 7]


In [49]:
print(arr[1:8:3])

[2 5 8]


In [50]:
print(arr[4:])

[ 5  6  7  8  9 10]


In [51]:
print(arr[:4])

[1 2 3 4]


In [52]:
print(arr[-3:-1])

[8 9]


In [53]:
print(arr[::2])

[1 3 5 7 9]


In [55]:
arr = np.array( [ [1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 1:4])   # 2,3,4 OR 7,8,9,10 OR 7,8,9
print(arr[1][1:4])

[7 8 9]
[7 8 9]


In [57]:
print(arr[0:2,2])     # arr[0:2][2]     prints 3,8 OR 

[3 8]


In [63]:
print(arr[0:2][1:4])     # not preferred.


[[ 6  7  8  9 10]]


In [61]:
print(arr[0:2,1:4])     # preferred.

[[2 3 4]
 [7 8 9]]


In [64]:
arr = np.array([1,2,3,4,5])
newArr = arr.copy()

print(arr)
print(newArr)

[1 2 3 4 5]
[1 2 3 4 5]


In [66]:
arr[0] = 76
print(arr)
print(newArr)

[76  2  3  4  5]
[1 2 3 4 5]


In [67]:
newArr[2] = 50
print(arr)
print(newArr)

[76  2  3  4  5]
[ 1  2 50  4  5]


In [68]:
arr = np.array([1,2,3,4,5])
newArr = arr.view()

print(arr)
print(newArr)

[1 2 3 4 5]
[1 2 3 4 5]


In [69]:
arr[0] = 76
print(arr)
print(newArr)

[76  2  3  4  5]
[76  2  3  4  5]


In [70]:
newArr[2] = 50
print(arr)
print(newArr)

[76  2 50  4  5]
[76  2 50  4  5]


In [73]:
arr = np.array([1,2,3,4,5])

copyArr = arr.copy()
viewArr = arr.view()

print(copyArr)
print(viewArr)

# If it returns "None", it is a copy and owns the data.
print(copyArr.base)    
print(viewArr.base)


[1 2 3 4 5]
[1 2 3 4 5]
None
[1 2 3 4 5]


In [74]:
# Iterating.
arr = np.array([1,2,3,4,5])
for i in arr:
    print(i)

1
2
3
4
5


In [77]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10


In [78]:
arr = np.array([[[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]])
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [79]:
arr = np.array([[[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [84]:
arr = np.array([[[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]])
for indx, x in np.ndenumerate(arr):
    print(indx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 10
(0, 2, 0) 11
(0, 2, 1) 12
(0, 2, 2) 13
(0, 2, 3) 14
(0, 2, 4) 15


In [85]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [86]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

arr = np.concatenate((arr1, arr2))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [87]:
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [90]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.stack((arr1,arr2), axis=1)
print(arr)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [91]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.stack((arr1,arr2))
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [93]:
arr1 = np.array([1,2,3,4,5,6])

arr = np.array_split(arr1,3)
print(arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [94]:
arr1 = np.array([1,2,3,4,5,6,7])

arr = np.array_split(arr1,3)
print(arr)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [95]:
arr1 = np.array([1,2,3,4,5,6])

arr = np.array_split(arr1,4)
print(arr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [96]:
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])


[1 2]
[3 4]
[5]
[6]


In [101]:
arr1 = np.array([[1,2],[3,4], [5,6],[7,8], [9,10]])

arr = np.array_split(arr1, 3)
print(arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]])]


In [102]:
arr = np.array([1,2,3,4,5,6,7])
srch = np.where(arr == 4)
print(srch)


(array([3], dtype=int64),)


In [104]:
arr = np.array([1,2,3,4,5,4,6,7,4])
srch = np.where(arr == 4)
print(srch)

(array([3, 5, 8], dtype=int64),)


In [105]:
print(arr[srch])

[4 4 4]


In [106]:
arr = np.array([1,2,3,4,5,6,7,8])
srch = np.where(arr %2 == 0)
print(srch)

(array([1, 3, 5, 7], dtype=int64),)


In [107]:
arr = np.array([1,2,3,4,5,6,7,8])
srch = np.where(arr %2 == 1)
print(srch)

(array([0, 2, 4, 6], dtype=int64),)


In [109]:
arr = np.array([5,6,8,9])
x = np.searchsorted(arr, 7)
print(x)


2


In [110]:
arr = np.array([8,6,9,5])
x = np.searchsorted(arr, 7)
print(x)


2


In [120]:
arr = np.array([4,5,6,8,9])
x = np.searchsorted(arr, 7, side="right")
print(x)


3


In [121]:
arr = np.array([1,3,5,7])
x = np.searchsorted(arr, [2,4])
print(x)


[1 2]


In [122]:
arr1 = np.array([8,6,9,5])
arr = np.sort(arr1)

print(arr)

[5 6 8 9]


In [123]:
arr1 = np.array(["strawberry", "apple", "orange", "banana",])
arr = np.sort(arr1)

print(arr)

['apple' 'banana' 'orange' 'strawberry']


In [124]:
arr1 = np.array([15,16,17,18])
filter = [True, False, True, False]

newArr = arr1[filter]
print(newArr)

[15 17]


In [125]:
arr1 = np.array([15,16,17,18])
filter = [True, False, False, True]

newArr = arr1[filter]
print(newArr)

[15 18]


In [128]:
arr1 = np.array([15,16,17,18])
filter = [True, False, False, True]

newArr = arr1[filter]
print(newArr)

[15 18]


In [131]:
arr1 = np.array([15,16,17,18, 19, 20])
filter = arr1 > 18

newArr = arr1[filter]
print(filter)
print(newArr)

[False False False False  True  True]
[19 20]


In [132]:
arr1 = np.array([15,16,17,18, 19, 20])
filter = arr1 %2 == 0

newArr = arr1[filter]
print(filter)
print(newArr)

[False  True False  True False  True]
[16 18 20]
